name: Deploy Latest

on:
  push:
    branches:
      - init-actions

jobs:
  deploy:
    name: Creating development deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Create Build
        run: |
          npm install
          npm run build
          npm run log
